### PR TITLE
Typos

### PR DESCRIPTION
**Pull request by PeteHaitch**

### CODE REVIEW

**Comment by LTLA** [comment]
Oh. Uh... that's because I wrote it in American English.

I could merge it now, or I could just wait for you to rack up a few more.

**Comment by PeteHaitch** [comment]
Stick an acute on it and you might argue it's French ... https://www.mathematiquesfaciles.com/probabilites_2_58226.htm
I've not been typo hunting systematically, just spotting the odd one as I make some notes

**Comment by LTLA** [comment]
Orchestrer l'analyse monocellulaire avec un bioconducteur?

**Comment by LTLA** [comment]
I take it no more are coming, so I'm just going to merge this in.

**Pull request merged**
