### PR TITLE
A couple of more text fixes

### PR DESCRIPTION
**Pull request by csoneson**
Addresses most of the points mentioned in #7

### CODE REVIEW

**Comment by LTLA** [comment]
> Now, say we have a different dimensionality reduction approach which has not yet been implemented with *SingleCellExperiment* objects in mind. For example, let's say we want to explicitly use the `umap()` function as implemented in the `uwot` package.

Seems like the original text was wrong, we have `runUMAP` that does exactly this.

**Comment by csoneson** [comment]
>Seems like the original text was wrong, we have runUMAP that does exactly this.

Yes; my attempt was to make a minimal change that would still illustrate the general approach, but remove the statement about `scater` using `umap`. But it's of course true that `uwot::umap` has already been implemented with SingleCellExperiment objects in mind...

**Comment by LTLA** [comment]
@robertamezquita merge and fix re. my comment above.

**Comment by csoneson** [comment]
Re: `chosen` in the data integration chapter: it is mentioned on lines 209 and 223, but never initialized and never used. Fix depends on whether the intention was to use a subset of the genes or not - if yes, I guess these two mentions should be changed to `chosen.hvgs` and an argument `subset.row` provided on lines 217-218; if not, those text lines should be modified.

**Pull request merged**
